apiVersion: v1
kind: Pod
metadata: 
  name: web-pod1
  labels: 
    env: qa
    application: web
    # container is a list so use - 
spec: 
  containers: 
  - name: webcont1
    image: docker.io/httpd
