apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx-server
spec:
  selector:
    matchLabels:
      app: nginx-server
  template:
    metadata:
      labels:
        app: nginx-server
    spec:
      containers:
      - name: nginx-server-container
        image: nginx-server-image:latest
        ports:
        - containerPort: 80
